continuing work on final project
AnnaPestova1/Sky_Event_front pull request #2
Opened 2024-01-23 20:14 UTC by AnnaPestova1

it's front end repository. back end is here: https://github.com/AnnaPestova1/Sky_Event_back/pull/2

2024-01-25 18:07 UTC, joseluiz requested changes
Hey @AnnaPestova1, I've reviewed your final project and left some comments on the pull request related to some minor issues on the front end side. Could you please take a look?

2024-01-25 18:07 UTC, joseluiz commented on src/components/api-data/SharedRow.jsx
> +  const date = new Date(data.date).toLocaleDateString();
The wrong event day is showing on the Sky Events page.
 <img width="1592" alt="Screenshot 2024-01-25 at 10 44 59" src="https://github.com/AnnaPestova1/Sky_Event_front/assets/377074/e3077445-bd6f-4ff5-ab3d-e6001ac6b697">

You should do this on line 17 of SharedRow.jsx file:
```
const date = new Date(data.date).toLocaleDateString(undefined, {
    timeZone: "UTC"
  });
```

2024-01-25 18:07 UTC, joseluiz commented on src/components/appData/EventForm.jsx
> +    let month = new Date(value.date).getUTCMonth();
The Date is not displayed when editing an event that the month is January. 
<img width="1269" alt="Screenshot 2024-01-25 at 10 49 16" src="https://github.com/AnnaPestova1/Sky_Event_front/assets/377074/fa99494c-e6b5-43fc-a41f-153e23283c9d">

You need to do this on line 20 of the EventForm.jsx file:
```
let month = new Date(value.date).getUTCMonth() + 1;
```
Because the getUTCMonth method returns the month starting with 0, so you need to add one to display the correct month.

2024-01-25 18:07 UTC, joseluiz commented on src/components/auth/Register.jsx
> +      .catch(error => {
When some error happens on user registration, no error is shown to the user, for example, if the user already exists. It would be nice to add notification here.
<img width="1719" alt="Screenshot 2024-01-25 at 13 28 18" src="https://github.com/AnnaPestova1/Sky_Event_front/assets/377074/6ab0c8a6-5a1a-40ac-a554-42c06ad6f4f2">

2024-01-25 18:07 UTC, joseluiz commented on src/components/auth/Register.jsx
> +        <Button type="submit">Login</Button>
Wouldn't this button be labeled as "Register" or "Submit"?

2024-01-25 18:07 UTC, joseluiz commented on src/components/auth/Login.jsx
> +      .catch(error => {
When some error happens on user authentication, no error is shown to the user. It would be nice to add notification here.
<img width="1654" alt="Screenshot 2024-01-25 at 13 32 44" src="https://github.com/AnnaPestova1/Sky_Event_front/assets/377074/3ddb45e9-f9f8-41fe-8628-c73a7387274e">

2024-02-10 23:10 UTC, AnnaPestova1 commented on src/components/api-data/SharedRow.jsx
> +  const date = new Date(data.date).toLocaleDateString();
fixing in final branch

2024-02-10 23:11 UTC, AnnaPestova1 commented on src/components/appData/EventForm.jsx
> +    let month = new Date(value.date).getUTCMonth();
fixing in later branch

2024-02-10 23:11 UTC, AnnaPestova1 commented on src/components/auth/Register.jsx
> +      .catch(error => {
added in later branch

2024-02-10 23:13 UTC, AnnaPestova1 commented on src/components/auth/Register.jsx
> +        <Button type="submit">Login</Button>
fixed in later branch

2024-02-10 23:13 UTC, AnnaPestova1 commented on src/components/auth/Login.jsx
> +      .catch(error => {
added in later branch

2024-02-15 15:33 UTC, merged